// <auto-generated>
//   This file was generated from Strings.resx.
//   To add or change strings, edit Strings.resx and regenerate (or update both files).
// </auto-generated>
#nullable enable
using System.Globalization;
using System.Resources;

namespace UI.Assets;

public static class Strings
{
    private static ResourceManager? _resourceManager;

    public static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager("UI.Assets.Strings", typeof(Strings).Assembly);

    public static CultureInfo? Culture { get; set; }

    private static string G(string key) =>
        ResourceManager.GetString(key, Culture) ?? key;

    // ── App / Main Window ──────────────────────────────────────────────────
    public static string AppTitle        => G(nameof(AppTitle));
    public static string AppLabel        => G(nameof(AppLabel));

    // ── Toolbar buttons ────────────────────────────────────────────────────
    public static string BtnOpenFolder   => G(nameof(BtnOpenFolder));
    public static string BtnSave         => G(nameof(BtnSave));
    public static string BtnSaveTip      => G(nameof(BtnSaveTip));
    public static string BtnReload       => G(nameof(BtnReload));
    public static string BtnReloadTip    => G(nameof(BtnReloadTip));
    public static string BtnHelp         => G(nameof(BtnHelp));
    public static string BtnHelpTip      => G(nameof(BtnHelpTip));

    // ── Undo / Redo ────────────────────────────────────────────────────────
    public static string UndoNothingToUndo => G(nameof(UndoNothingToUndo));
    public static string UndoNothingToRedo => G(nameof(UndoNothingToRedo));
    public static string UndoTip           => G(nameof(UndoTip));
    public static string RedoTip           => G(nameof(RedoTip));

    // ── View menu ──────────────────────────────────────────────────────────
    public static string MenuView         => G(nameof(MenuView));
    public static string MenuViewDistList => G(nameof(MenuViewDistList));
    public static string MenuViewDetail   => G(nameof(MenuViewDetail));
    public static string MenuViewError    => G(nameof(MenuViewError));
    public static string MenuViewRight    => G(nameof(MenuViewRight));

    // ── Panels ─────────────────────────────────────────────────────────────
    public static string PanelCloseTip   => G(nameof(PanelCloseTip));
    public static string PanelProperties => G(nameof(PanelProperties));

    // ── Status bar ─────────────────────────────────────────────────────────
    public static string StatusLoaded    => G(nameof(StatusLoaded));
    public static string StatusSaving    => G(nameof(StatusSaving));
    public static string StatusSaved     => G(nameof(StatusSaved));
    public static string StatusNoChanges => G(nameof(StatusNoChanges));

    // ── Dialogs ────────────────────────────────────────────────────────────
    public static string DialogSelectFolder   => G(nameof(DialogSelectFolder));
    public static string DialogUnsavedChanges => G(nameof(DialogUnsavedChanges));
    public static string DialogSave           => G(nameof(DialogSave));
    public static string DialogDiscard        => G(nameof(DialogDiscard));
    public static string DialogCancel         => G(nameof(DialogCancel));
    public static string DialogTabHasUnsaved  => G(nameof(DialogTabHasUnsaved));
    public static string DialogUnsavedPrompt  => G(nameof(DialogUnsavedPrompt));

    // ── Tabs ───────────────────────────────────────────────────────────────
    public static string TabClickToReload => G(nameof(TabClickToReload));
    public static string TabPin           => G(nameof(TabPin));
    public static string TabUnpin         => G(nameof(TabUnpin));
    public static string TabClose         => G(nameof(TabClose));
    public static string TabCloseAll      => G(nameof(TabCloseAll));
    public static string TabCloseOthers   => G(nameof(TabCloseOthers));
    public static string TabCloseLeft     => G(nameof(TabCloseLeft));
    public static string TabCloseRight    => G(nameof(TabCloseRight));

    // ── Shared column / badge labels ───────────────────────────────────────
    public static string ColItem        => G(nameof(ColItem));
    public static string ColChance      => G(nameof(ColChance));
    public static string BtnAddItem     => G(nameof(BtnAddItem));
    public static string TipItemRolls   => G(nameof(TipItemRolls));
    public static string TipUniqueItems => G(nameof(TipUniqueItems));

    // ── Container control ──────────────────────────────────────────────────
    public static string CCProcBadge  => G(nameof(CCProcBadge));
    public static string CCSettings   => G(nameof(CCSettings));
    public static string CCRolls      => G(nameof(CCRolls));
    public static string CCJunkRolls  => G(nameof(CCJunkRolls));
    public static string CCFillRand   => G(nameof(CCFillRand));
    public static string CCProcedural => G(nameof(CCProcedural));
    public static string CCNoAmmo     => G(nameof(CCNoAmmo));
    public static string CCItems      => G(nameof(CCItems));
    public static string CCJunk       => G(nameof(CCJunk));
    public static string CCProcLists  => G(nameof(CCProcLists));

    // ── Distribution list control ──────────────────────────────────────────
    public static string DLHeader             => G(nameof(DLHeader));
    public static string DLExpandAll          => G(nameof(DLExpandAll));
    public static string DLCollapseAll        => G(nameof(DLCollapseAll));
    public static string DLSearch             => G(nameof(DLSearch));
    public static string DLTypeHeader         => G(nameof(DLTypeHeader));
    public static string DLTypeAll            => G(nameof(DLTypeAll));
    public static string DLTypeRooms          => G(nameof(DLTypeRooms));
    public static string DLTypeCaches         => G(nameof(DLTypeCaches));
    public static string DLTypeProfessions    => G(nameof(DLTypeProfessions));
    public static string DLTypeProcedural     => G(nameof(DLTypeProcedural));
    public static string DLTypeItems          => G(nameof(DLTypeItems));
    public static string DLContentHeader      => G(nameof(DLContentHeader));
    public static string DLFilterProcList     => G(nameof(DLFilterProcList));
    public static string DLFilterRolls        => G(nameof(DLFilterRolls));
    public static string DLFilterItems        => G(nameof(DLFilterItems));
    public static string DLFilterJunk         => G(nameof(DLFilterJunk));
    public static string DLFilterProcedural   => G(nameof(DLFilterProcedural));
    public static string DLStructureHeader    => G(nameof(DLStructureHeader));
    public static string DLNoContent          => G(nameof(DLNoContent));
    public static string DLInvalid            => G(nameof(DLInvalid));
    public static string DLDistItems          => G(nameof(DLDistItems));
    public static string DLMenuOpen           => G(nameof(DLMenuOpen));
    public static string DLMenuOpenSelected   => G(nameof(DLMenuOpenSelected));
    public static string DLMenuNewFolder      => G(nameof(DLMenuNewFolder));
    public static string DLMenuNewSubfolder   => G(nameof(DLMenuNewSubfolder));
    public static string DLMenuMoveToFolder   => G(nameof(DLMenuMoveToFolder));
    public static string DLMenuRemoveFromFolder => G(nameof(DLMenuRemoveFromFolder));
    public static string DLMenuRenameFolder   => G(nameof(DLMenuRenameFolder));
    public static string DLMenuDeleteFolder   => G(nameof(DLMenuDeleteFolder));
    public static string DLMenuExpandAll      => G(nameof(DLMenuExpandAll));
    public static string DLMenuCollapseAll    => G(nameof(DLMenuCollapseAll));

    // ── Distribution detail control ────────────────────────────────────────
    public static string DDEmptyTitle     => G(nameof(DDEmptyTitle));
    public static string DDEmptySubtitle  => G(nameof(DDEmptySubtitle));
    public static string DDRolls          => G(nameof(DDRolls));
    public static string DDShop           => G(nameof(DDShop));
    public static string DDNoAmmo         => G(nameof(DDNoAmmo));
    public static string DDMaxMap         => G(nameof(DDMaxMap));
    public static string DDStash          => G(nameof(DDStash));
    public static string DDExpandAll      => G(nameof(DDExpandAll));
    public static string DDCollapseAll    => G(nameof(DDCollapseAll));
    public static string DDShowEmpty      => G(nameof(DDShowEmpty));
    public static string DDShowEmptyTip   => G(nameof(DDShowEmptyTip));
    public static string DDAutoFilter     => G(nameof(DDAutoFilter));
    public static string DDAutoFilterTip  => G(nameof(DDAutoFilterTip));
    public static string DDClear          => G(nameof(DDClear));
    public static string DDClearTip       => G(nameof(DDClearTip));
    public static string DDFilterProcList   => G(nameof(DDFilterProcList));
    public static string DDFilterRolls      => G(nameof(DDFilterRolls));
    public static string DDFilterItems      => G(nameof(DDFilterItems));
    public static string DDFilterJunk       => G(nameof(DDFilterJunk));
    public static string DDFilterProcedural => G(nameof(DDFilterProcedural));
    public static string DDFilterInvalid    => G(nameof(DDFilterInvalid));
    public static string DDDistItemsLabel   => G(nameof(DDDistItemsLabel));
    public static string DDTabItems         => G(nameof(DDTabItems));
    public static string DDTabJunk          => G(nameof(DDTabJunk));
    public static string DDReferencedBy     => G(nameof(DDReferencedBy));

    // ── Error list control ─────────────────────────────────────────────────
    public static string ELHeader          => G(nameof(ELHeader));
    public static string ELErrorsDefault   => G(nameof(ELErrorsDefault));
    public static string ELWarningsDefault => G(nameof(ELWarningsDefault));
    public static string ELErrorsFmt       => G(nameof(ELErrorsFmt));
    public static string ELWarningsFmt     => G(nameof(ELWarningsFmt));
    public static string ELCopySelected    => G(nameof(ELCopySelected));
    public static string ELCopyAll         => G(nameof(ELCopyAll));
    public static string ELColType         => G(nameof(ELColType));
    public static string ELColCode         => G(nameof(ELColCode));
    public static string ELColContext      => G(nameof(ELColContext));
    public static string ELColMessage      => G(nameof(ELColMessage));
    public static string ELColFile         => G(nameof(ELColFile));

    // ── Help window ────────────────────────────────────────────────────────
    public static string HelpTitle         => G(nameof(HelpTitle));
    public static string HelpHeader        => G(nameof(HelpHeader));
    public static string HelpWelcome       => G(nameof(HelpWelcome));
    public static string HelpGettingStarted => G(nameof(HelpGettingStarted));
    public static string HelpDistExplorer  => G(nameof(HelpDistExplorer));
    public static string HelpFilters       => G(nameof(HelpFilters));
    public static string HelpDetailView    => G(nameof(HelpDetailView));
    public static string HelpContainers    => G(nameof(HelpContainers));
    public static string HelpEditing       => G(nameof(HelpEditing));
    public static string HelpSaving        => G(nameof(HelpSaving));
    public static string HelpErrorList     => G(nameof(HelpErrorList));
    public static string HelpShortcuts     => G(nameof(HelpShortcuts));
    public static string HelpItemsExplorer => G(nameof(HelpItemsExplorer));
    public static string HelpItemsDetail   => G(nameof(HelpItemsDetail));

    // ── Items list control ─────────────────────────────────────────────────
    public static string ILHeader          => G(nameof(ILHeader));
    public static string ILSearch          => G(nameof(ILSearch));
    public static string ILItemTypeHeader  => G(nameof(ILItemTypeHeader));
    public static string ILFilterItems     => G(nameof(ILFilterItems));
    public static string ILFilterJunk      => G(nameof(ILFilterJunk));
    public static string ILMenuOpen        => G(nameof(ILMenuOpen));
    public static string ILMenuOpenSelected => G(nameof(ILMenuOpenSelected));

    // ── Items detail control ───────────────────────────────────────────────
    public static string IDOccurrences          => G(nameof(IDOccurrences));
    public static string IDColDistribution      => G(nameof(IDColDistribution));
    public static string IDColContainer         => G(nameof(IDColContainer));
    public static string IDColItemType          => G(nameof(IDColItemType));
    public static string IDColType              => G(nameof(IDColType));
    public static string IDColChance            => G(nameof(IDColChance));
    public static string IDDistLevel            => G(nameof(IDDistLevel));
    public static string IDAddDistPlaceholder   => G(nameof(IDAddDistPlaceholder));
    public static string IDAddContainerPlaceholder => G(nameof(IDAddContainerPlaceholder));
    public static string IDBtnAdd               => G(nameof(IDBtnAdd));
    public static string IDAutoFilter           => G(nameof(IDAutoFilter));
    public static string IDAutoFilterTip        => G(nameof(IDAutoFilterTip));

    // ── View menu additions ────────────────────────────────────────────────
    public static string MenuViewItemList  => G(nameof(MenuViewItemList));

    // ── Proc list entry control ────────────────────────────────────────────
    public static string PEDistribution   => G(nameof(PEDistribution));
    public static string PEOpenInPropsTip => G(nameof(PEOpenInPropsTip));
    public static string PEResolved       => G(nameof(PEResolved));
    public static string PEMinMax         => G(nameof(PEMinMax));
    public static string PEWeight         => G(nameof(PEWeight));
    public static string PEForceTiles     => G(nameof(PEForceTiles));
    public static string PEForceRooms     => G(nameof(PEForceRooms));
    public static string PEForceItems     => G(nameof(PEForceItems));
}
